pipeline {
    agent any

    environment {
        // Retrieve Docker credentials
        DOCKER_CREDENTIALS = credentials("docker_password")
        DOCKER_USERNAME = "${DOCKER_CREDENTIALS_USR}" // Assuming the credential ID is "docker_password"
        DOCKER_PASSWORD = "${DOCKER_CREDENTIALS_PSW}" // Assuming the credential ID is "docker_password"
    }

    stages {
        stage('Tag image') {
            steps {
                script {
                    GIT_TAG = sh([script: 'git fetch --tag && git tag', returnStdout: true]).trim()
                    MAJOR_VERSION = sh([script: 'git tag | cut -d . -f 1', returnStdout: true]).trim()
                    MINOR_VERSION = sh([script: 'git tag | cut -d . -f 2', returnStdout: true]).trim()
                    PATCH_VERSION = sh([script: 'git tag | cut -d . -f 3', returnStdout: true]).trim()
                }
                sh "docker build -t ${DOCKER_USERNAME}/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION} -f /Dockerfile ."
            }
        }
    }
}
